mkxp_shaders = files(
    'common.h',
    'minimal.vert',
    'simple.vert',
    'simple.frag',
    'simpleMatrix.vert',
    'simpleColor.vert',
    'simpleColor.frag',
    'simpleAlpha.frag',
    'simpleAlphaUni.frag',
    'flatColor.frag',
    'bitmapBlit.frag',
    'sprite.vert',
    'sprite.frag',
    'plane.frag',
    'tilemap.vert',
    'flashMap.frag',
    'gray.frag',
    'hue.frag',
    'blur.frag',
    'blurH.vert',
    'blurV.vert',
    'trans.frag',
    'transSimple.frag',
    'obscured.frag'
)

mkxp_sources += embed.process(mkxp_shaders, extra_args: ['shader'])
