# Build options
option(
    'gfx_backend',
    type: 'combo',
    choices: ['gl', 'gles'],
    value: 'gl',
    description: 'Whether use OpenGL or OpenGL ES'
)
option(
    'workdir_current',
    type: 'boolean',
    value: false,
    description: 'Keep Current Working Directory on startup'
)
option(
    'steam',
    type: 'boolean',
    value: false,
    description: 'Enable Steamworks support'
)
option(
    'copy_gamefiles',
    type: 'boolean',
    value: false,
    description: 'Copy game files to install directory'
)

# Ruby MRI options
option(
    'mri_version',
    type: 'string',
    value: '3.4',
    description: 'Ruby version to link with'
)
option(
    'mri_libname',
    type: 'string',
    value: 'ruby',
    description: 'Ruby library name to find'
)
option(
    'mri_libpath',
    type: 'string',
    value: '',
    description: 'Ruby library path to find'
)
option(
    'mri_includes',
    type: 'array',
    value: [],
    description: 'Include paths to Ruby headers'
)
